"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from 'react-redux';
import store from '../redux/store';
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <Navbar /> */}
        <Provider store={store}>
        <Navbar />
          {children}
        </Provider>
      </body>
    </html>
  );
}

