export const USER_SIGNUP_REQUEST= "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS= "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL= "USER_SIGNUP_FAIL";
export const USER_SIGNUP_RESET= "USER_SIGNUP RESET";

export const USER_SIGNIN_REQUEST= "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS= "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL= "USER_SIGIN_FAIL";
export const USER_SIGNIN_RESET= "USER_SIGNIN RESET";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";
export const USER_LOGOUT_RESET = "USER_LOGOUT_RESET";

export const CONFIRM_REQUEST= "CONFIRM_REQUEST";
export const CONFIRM_SUCCESS= "CONFIRM_SUCCESS";
export const CONFIRM_FAIL= "CONFIRM_FAIL";
export const CONFIRM_RESET= "CONFIRM_RESET";

export const PASSWORD_FORGOT_REQUEST= "PASSWORD_FORGOT_REQUEST";
export const PASSWORD_FORGOT_SUCCESS= "PASSWORD_FORGOT_SUCCESS";
export const PASSWORD_FORGOT_FAIL= "PASSWORD_FORGOT_FAIL";
export const PASSWORD_FORGOT_RESET= "PASSWORD_FORGOT_RESET";

export const PASSWORD_RESET_REQUEST= "PASSWORD_RESET_REQUEST";
export const PASSWORD_RESET_SUCCESS= "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_FAIL= "PASSWORD_RESET_FAIL";
export const PASSWORD_RESET_RESET= "PASSWORD_RESET_RESET";